# Generated by Django 3.1.3 on 2020-11-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_rubric_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='news/', verbose_name='изображение'),
        ),
    ]
